version: '3.9'

services:
  back:
    build:
      context: .
      dockerfile: dockerfile_back
    ports:
      - '3000:3000'
    command: ['sh', '-c', ' npm run start:dev']

  front:
    build:
      context: .
      dockerfile: dockerfile_front
    ports:
      - '8080:5173'
    depends_on:
      - back
    command: ['sh', '-c', 'npm run dev -- --host']
